### ISSUE TITLE
Gm_construct and gm_flatgrass still crashes

### ISSUE THREAD

**Issue by Strelok111** [BlueAmulet/SourceRTXTweaks#1]
First of all
THANK YOU SO MUCH
Second of all
Do you know what is causing these crashes? been messing around with it and i havent found anything related to the crash

**Comment by BlueAmulet** [comment]
Might have to do with the fact that these maps don't actually use textured skyboxes. I was able to force the maps to load but since there's no texture for the skybox, there's no real point in using these maps with RTX Remix.

![gm_construct0001](https://user-images.githubusercontent.com/43395286/212500634-11ef0cc2-3a49-4710-bc65-036f6177a01c.jpg)
Forgive my use of the sidewalk for some light.

**Comment by BlueAmulet** [comment]
Well never mind, only some of the shader sky maps are actually dark, some seem to work okay, and some are highly highly broken.

Warning: This a very dumb patch and just outright disables some code I haven't investigated at all. But it does seem to only be invoked on these shader sky maps. It completely breaks GMod when not using RTX Remix.
**shaderapidx9.dll:**
3CFD3: Change `8B 45 10` to `90 31 C0`

![gm_flatgrass0003](https://user-images.githubusercontent.com/43395286/212501614-eae6cd74-4cca-439c-8dae-2c5f7010dcc3.jpg)

I'll keep investigating this issue and try to make a more proper patch though.

**Comment by BlueAmulet** [comment]
It turns out you can just go into garrysmod\bin and rename game_shader_generic_garrysmod.dll to something else to bypass the crashes. I'll add this to the readme under a Recommendations section or similar and then close this.

**Comment by bluedogz162** [comment]
You could also use sv_skyname, as it was somewhat recently patched to update the skybox on the fly
